server:
  port: 8090
  servlet:
    context-path: /examen
spring:
  datasource:
    initialize: true
    initialization-mode: always
    platform: h2
    url: "jdbc:h2:file:./data.sql"

    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: none
  h2:
    console:
      enabled: true
      path: /h2-console